image: gradle:alpine
stages:
    - build
    - test

before_script:
    - export GRADLE_USER_HOME="$(pwd)/.gradle"

build:
    stage: build
    script: ./gradlew --build-cache assemble
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - build
            - .gradle
    artifacts:
        paths:
            - build/libs/*.jar

test:
    stage: test
    script:
        - ./gradlew check
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - build
            - .gradle
    artifacts:
        paths:
            - build/reports/*
            - build/jacocoHTML/*

